#!/usr/bin/env bash

workspaces() {

	workspace_windows=$(hyprctl workspaces -j | jq "sort_by(.id)")
	number_of_workspaces=$(echo "$workspace_windows" | jq length)
	active_workspace=$(source ~/.config/eww/bar/scripts/get-active-workspace)
	workspace_widgets=""

	for ((c = 0; c < $number_of_workspaces; c++)); do
		current_workspace_id=$(echo $workspace_windows | jq ".[$c].id")
		if [[ current_workspace_id -eq $active_workspace ]]; then
			workspace_widgets+="(button :class \"active-workspace-button\" :width 25 :onclick \"hyprctl dispatch workspace $current_workspace_id\" \"\")"
		else
			workspace_widgets+="(button :class \"workspace-button\" :halign \"center\" :onclick \"hyprctl dispatch workspace $current_workspace_id\" \"\")"
		fi
	done

	echo "(box :orientation \"h\" :spacing 5 $workspace_widgets)"
}
workspaces
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	workspaces
done
