---
- name: Install GUI applictions with Flatpak
  hosts: localhost

  tasks:
  - name: Install multiple packages
    community.general.flatpak:
      name:
        - org.mozilla.firefox
        - com.bitwarden.desktop 
        - com.brave.Browser     
        - md.obsidian.Obsidian  
        - org.signal.Signal     
        - com.valvesoftware.Steam
        - com.spotify.Client    
